source 'http://rubygems.org'

gem 'rails', '>=2.3.5', '<3.0.0'

 
gem 'authlogic', '>=0.1.0'
gem 'builder'
gem 'columnize'
gem 'crack'
gem 'curb'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'haml'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem 'linecache'
gem 'marc'
gem 'mime-types'
gem 'multipart-post'
gem 'nokogiri'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rcov'
gem 'RedCloth'
gem 'rsolr'
gem 'rsolr-ext'
gem 'solr-ruby'
gem 'sqlite3-ruby', '1.3.0'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate'
gem 'xml-simple'
source 'http://gemcutter.org'

gem 'block_helpers'


