source 'http://rubygems.org'

gem 'rails', '=2.3.11'

 
gem 'authlogic', '>=0.1.0'
gem 'builder', '=2.1.2'
gem 'columnize'
gem 'crack'
gem 'curb'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'haml'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem 'linecache'
gem 'marc'
gem 'mime-types'
gem 'multipart-post'
gem 'nokogiri'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rcov'
gem 'RedCloth'
gem 'rsolr', '=0.12.1'
gem 'rsolr-ext', '=0.12.0'
gem 'solr-ruby'
gem 'sqlite3-ruby', '1.2.5'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate'
gem 'xml-simple'

gem 'block_helpers'


