development:
  default:
    url: http://salt-prod.stanford.edu/chris_solr  
  fulltext:
    url: http://salt-prod.stanford.edu/chris_solr
test: &TEST
  default:
    url: http://localhost:8983/solr/development
  fulltext:
    url: http://localhost:8983/solr/development
production:
  default:
    url: http://salt-prod.stanford.edu/chris_solr
  fulltext:
    url: http://salt-prod.stanford.edu/chris_solr
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
