development:
  default:
    url: http://localhost:8983/solr/development
  fulltext:
    url: http://localhost:8983/solr/development
test: &TEST
  default:
    url: http://localhost:8983/solr/development
  fulltext:
    url: http://localhost:8983/solr/development
production:
  default:
    url: http://your.production.com/solr/
  fulltext:
    url: http://your.production.com/solr/
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
